server:
  port: 8080
spring:
  application:
    name: my-test

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/MyPostgreSQL?stringtype=unspecified&useSSL=false&useUnicode=true&characterEncoding=utf-8&reWriteBatchedInserts=true
    username: root
    password: admin

mybatis-plus:
  #驼峰命名
#  configuration:
#    map-underscore-to-camel-case: true
  #mapper.xml文件扫描
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.zrr.entity
  #  global-config:
  #    db-config:
  #      id-type: auto 数据库ID自增

















